name: build

on:
  push:

env:
  BUILD_TYPE: Release
  SK_VERSION: nover

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    env:
      CC: gcc-12
      CXX: g++-12

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure stuff
        run: |
          sudo apt install g++-12
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/tmp ..
          echo "SK_VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . -j 6

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . --target install
          cd ../tmp
          ./idtech_toolset
          rm idtech_toolset.config
          mv ../LICENSE .
          # mv ../README.md .
          tar -cvaf ../idTechToolset-v${{env.SK_VERSION}}-linux-amd64.tar.xz .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: idTechToolset-linux-amd64
          path: ${{github.workspace}}/idTechToolset-v${{env.SK_VERSION}}-linux-amd64.tar.xz
          retention-days: 5

  build-widle:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure stuff
        run: |
          choco install ninja
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}} ..
          echo "SK_VERSION=$(Get-Content -Path ./version)" >> $env:GITHUB_ENV
        env:
          CC: clang
          CXX: clang++
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . -j 6

      - name: Install
        run: |
          cmake --build build --target install
          bin/idtech_toolset.exe
          del bin/idtech_toolset.config
          copy LICENSE bin/LICENSE
          # copy README.md bin/README.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: idTechToolset-v${{env.SK_VERSION}}-win64
          path: ${{github.workspace}}/bin
          retention-days: 5
