name: release nightly

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed
    branches:
      - master

env:
  SK_VERSION: nover

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yaml
        branch: ${{ github.event.release.target_commitish }}
        workflow_conclusion: success

    - name: Import signature key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GHA_GPG_KEY }}
        passphrase: ${{ secrets.GHA_GPG_PWD }}

    - name: Move artifacts to workspace
      run: |
        for file in *; do
          if [ -d $file ]; then
              pushd $file
              if [[ $file == *-win64 ]]; then
                7z a ../$file.7z .
                gpg --detach-sign ../$file.7z
                # 7z a ../$file-modulesonly.7z '-ir!*.spk'
              else
                BASENAME=$(basename *.tar.xz .tar.xz)
                echo "SK_VERSION=$(echo ${BASENAME} | cut -d'-' -f 2)" >> $GITHUB_ENV
                # tar -xf *.tar.xz
                # 7z a ../${BASENAME}-modulesonly.7z '-ir!*.spk'
                mv *.tar.xz ..
                gpg --detach-sign ../*.tar.xz
              fi
              popd
          fi
        done

    - name: Remove old nightly release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: nightly
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait a sec
      run: sleep 2

    - name: Release them
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.xz
          *.7z
          *.sig
        tag_name: nightly
        name: nightly ${{env.SK_VERSION}}
